/** Operator-facing defaults. User relay lists and deployment env values override these where supported. */
export const SERVICE_CONFIG = {
  localRelayPath: '/relay',
  relaySyncApiPath: '/relay-sync',
  publicOrigin: 'https://nosu.social',
  groupsDevUrl: 'http://localhost:8080/',
  socialRelays: [
    'wss://relay.primal.net',
    'wss://relay.nostr.com',
    'wss://nos.lol',
    'wss://relay.snort.social',
    'wss://relay.damus.io',
    'wss://relay.nostr.band',
    'wss://relay.nos.social',
    'wss://nostr.bitcoiner.social',
    'wss://nostr.mom',
    'wss://relay2.veganostr.com',
    'wss://nostr.data.haus',
    'wss://poster.place/relay',
  ],
  signerRendezvousRelay: 'wss://relay.powr.build',
  dmRelays: ['wss://nos.lol', 'wss://nostr.mom'],
  zapRelays: [
    'wss://nostr-pub.wellorder.net',
    'wss://nostr.oxtr.dev',
    'wss://relay.mostr.pub',
  ],
  searchRelays: ['wss://search.nos.today'],
  indexerRelays: ['wss://user.kindpag.es'],
  listSyncRelay: 'wss://purplepag.es',
  blossomServers: [
    'https://blossom.nostr.build',
    'https://cdn.hzrd149.com',
    'https://cdn.nostrcheck.me',
  ],
  nostrResolver: 'https://njump.me',
  quoteOrigin: 'https://nostrich.org',
  oembed: {
    youtube: 'https://www.youtube.com/oembed',
    vimeo: 'https://vimeo.com/api/oembed.json',
  },
  embeds: {
    youtube: 'https://www.youtube-nocookie.com/embed',
    youtubePoster: 'https://i.ytimg.com/vi',
    vimeo: 'https://player.vimeo.com/video',
    odysee: 'https://odysee.com/$/embed',
    rumble: 'https://rumble.com/embed',
    twitchClips: 'https://clips.twitch.tv/embed',
    twitchPlayer: 'https://player.twitch.tv/',
    twitchParent: 'nostrich.org',
    dailymotion: 'https://geo.dailymotion.com/player.html',
    bitchute: 'https://www.bitchute.com/embed',
    archive: 'https://archive.org/embed',
    kick: 'https://player.kick.com',
    spotify: 'https://open.spotify.com/embed',
    soundcloud: 'https://soundcloud.com',
    soundcloudPlayer: 'https://w.soundcloud.com/player/',
    wavlake: 'https://embed.wavlake.com',
    applePodcasts: 'https://embed.podcasts.apple.com',
    appleMusic: 'https://embed.music.apple.com',
  },
  fonts: {
    googleCss: 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&display=swap',
    googleStatic: 'https://fonts.gstatic.com',
  },
} as const
